"""next_check column added for CardModel

Revision ID: 5f314105f9fc
Revises: 3ab54f9a19ad
Create Date: 2020-06-07 11:42:47.084739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f314105f9fc'
down_revision = '3ab54f9a19ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('next_check', sa.Date(), nullable=False))
    op.alter_column('cards', 'board_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'board_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('cards', 'next_check')
    # ### end Alembic commands ###
