"""Added new FK to BoardModel to link to UserModel

Revision ID: bf46961c0b7d
Revises: 5f314105f9fc
Create Date: 2020-06-10 17:26:03.437441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf46961c0b7d'
down_revision = '5f314105f9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_boards_user_id_users'), 'boards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_boards_user_id_users'), 'boards', type_='foreignkey')
    op.drop_column('boards', 'user_id')
    # ### end Alembic commands ###
