"""Added SuperMemo2 info to db

Revision ID: 39c798e1d447
Revises: bf46961c0b7d
Create Date: 2020-07-07 17:43:06.490696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c798e1d447'
down_revision = 'bf46961c0b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('quality', sa.Integer(), nullable=False))
    op.alter_column('cards', 'next_check',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'next_check',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('cards', 'quality')
    # ### end Alembic commands ###
